name: on-push
on: [push]
jobs: 
  lerna-build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
      - run: npx lerna bootstrap
      - run: npx lerna run build 
  lerna-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
      - run: npm install @typescript-eslint/eslint-plugin@latest --save-dev
      - run: npx lerna run lint
